#!/bin/sh
helptext="USAGE: intuitype SOURCE DEST [STYLESHEET]"

if [ $# -ge 2 ]
then
    ruby /usr/local/lib/intuitype/generate.rb $3 < $1 | ps2pdf -dPDFSETTINGS=/printer - $2
else
    echo "$helptext"
fi
